@url = http://127.0.0.1:5000/auth
###
GET {{url}}/
#Returns Nothing

###
POST {{url}}/signup
Content-Type: application/json

{
    "name": "Noel jose",    
    "email": "noe2hl@gmail.com",
    "password": "Mirage20#@"

}

###
GET {{url}}/verify?token=eyJhbGciOiJIUzI1NiJ9.ODhjZmIxZTYzZTJkODNlMWE4NzZjMDFjOWMwNTU0N2Q1YjQ4NjQwNWQ3NzBlNzkxMDQxZmRjYjNmZGMxOWUzMTJkMzUyOTNiY2NlNWNiMzRhYTQ2NTUyYWE1Y2YwMTkzMjZiMzgwMjZhNTY1ZmI4MGVhYjNhMTU4NDg4NmM4Yjk4MmI4NmI3NmM3YzhkYTEyOWQ5OGNmM2FhNmQ2NDZjMmVlOTY2MzVhMzRkOThhOTBlNjY4Yjk5NzhmYTE4NWZiYTE1MzA0MDViMjQzZWJiOTJlNWY0MTA3MjU1OTlkMDZjMDcyMTFlODk3OTFmNjVi.jU6QD9BhvhsL_wOrh_UN-xguAxZ6z3lZ57fO25MED7k

###
POST {{url}}/login
Content-Type: application/json

{
    "email": "noel@gmail.com",
    "password": "Mirage20#@"
}


###
POST {{url}}/resetpassword
Content-Type: application/json

{
    "email": "noel@gmail.com"
}

###
POST {{url}}/reverification
Content-Type: application/json

{
    "email": "noe2l@gmail.com"
}

