@url = http://127.0.0.1:5000/auth
###
GET {{url}}/
#Returns Nothing

###
POST {{url}}/signup
Content-Type: application/json

{
    "name": "Noel jose",    
    "email": "noe2hl@gmail.com",
    "password": "Mirage20#@"

}

###
GET {{url}}/verify?token=eyJhbGciOiJIUzI1NiJ9.ZmMwNDY1YzZiZGM4OGYyZDQ5Y2U4MTI0NTcxZDNkOWE1NjA4Y2E3MmNiMmNkZjExN2Y5YmNkYWVhOWQxMzIxZTRjZGE5ZTNmYzVmNzRkMzZlOGMzYjhmODUwNzkyZjIzZmM3ZjA4Njg5NDFlYTUzMGY5OWM0ZWZiZjAzZDlmMWQwNGZlZDgyMDdkNzgwMzk4NDM5YjYwMTg3ZTkyNmU5Y2Q0ZTQwNTc3Zjc0YzEwZTRjYmY0ZWU1OTE3YzY4ODAxYjllMjlhZTg2YWZjMDc3ZTE3NmI3MDFlYmExNThjZTUzNzhhYWQ1ZmU5OGVmOTgw.0p_sbRHhLiI9RC4DSY9BRxVuh95v4N_BNGrjLhNgtq4

###
POST {{url}}/login
Content-Type: application/json

{
    "email": "noe2hl@gmail.com",
    "password": "Mirage20#@"
}


###
POST {{url}}/resetpassword
Content-Type: application/json

{
    "email": "noel@gmail.com"
}

###
POST {{url}}/reverification
Content-Type: application/json

{
    "email": "noe2l@gmail.com"
}

